<?php

use Spark\Features;
use App\Models\Team;

return [

    /*
    |--------------------------------------------------------------------------
    | Spark Path
    |--------------------------------------------------------------------------
    |
    | This configuration option determines the URI at which the Spark billing
    | portal is available. You are free to change this URI to a value that
    | you prefer. You shall link to this location from your application.
    |
    */

    'path' => 'billing',

    /*
    |--------------------------------------------------------------------------
    | Spark Middleware
    |--------------------------------------------------------------------------
    |
    | These are the middleware that requests to the Spark billing portal must
    | pass through before being accepted. Typically, the default list that
    | is defined below should be suitable for most Laravel applications.
    |
    */

    'middleware' => ['web', 'auth'],

    /*
    |--------------------------------------------------------------------------
    | Branding
    |--------------------------------------------------------------------------
    |
    | These configuration values allow you to customize the branding of the
    | billing portal, including the primary color and the logo that will
    | be displayed within the billing portal. This logo value must be
    | the absolute path to an SVG logo within the local filesystem.
    |
    */

    'brand' =>  [
        'logo' => realpath(__DIR__.'/../public/img/Manage-It-Pro-Ltd-logo.svg'),
        'color' => 'bg-purple-500',
    ],

    /*
    |--------------------------------------------------------------------------
    | Proration Behavior
    |--------------------------------------------------------------------------
    |
    | This value determines if charges are prorated when making adjustments
    | to a plan such as incrementing or decrementing the quantity of the
    | plan. This also determines proration behavior if changing plans.
    |
    */

    'prorates' => true,

    /*
    |--------------------------------------------------------------------------
    | Features
    |--------------------------------------------------------------------------
    |
    | Some of Spark's features are optional. You may disable the features by
    | removing them from this array. By removing features from this array
    | you can customize your Spark experience for your own application.
    |
    */

    'features' => [
        Features::billingAddressCollection(),
        Features::mustAcceptTerms(),
        Features::euVatCollection(['home-country' => 'GB']),
        Features::receiptEmails(['custom-addresses' => true]),
        Features::paymentNotificationEmails(),
    ],


    /*
    |--------------------------------------------------------------------------
    | Receipt Configuration
    |--------------------------------------------------------------------------
    |
    | The following configuration options allow you to configure the data that
    | appears in PDF receipts generated by Spark. Typically, this data will
    | include a company name as well as your company contact information.
    |
    */

    'receipt_data' => [
        'vendor' => 'Manage It Pro Ltd',
        'product' => 'Manage It Pro',
        'street' => ' 15 Oakwood Hill Industrial Estate',
        'location' => 'Loughton IG10 3TZ',
        'phone' => '07804 207 019',
    ],

    /*
    |--------------------------------------------------------------------------
    | Spark Billable
    |--------------------------------------------------------------------------
    |
    | Below you may define billable entities supported by your Spark driven
    | application. The Stripe edition of Spark currently only supports a
    | single billable model entity (team, user, etc.) per application.
    |
    | In addition to defining your billable entity, you may also define its
    | plans and the plan's features, including a short description of it
    | as well as a "bullet point" listing of its distinctive features.
    |
    */

    'billables' => [

        'team' => [
            'model' => Team::class,

            'default_interval' => 'monthly',

            'plans' => [
                [
                    'name' => 'Manage It Pro Removals',
                    'short_description' => 'Manage It Pro Removals License',
                    'monthly_id' => 'price_1Jj3pEI2g5BS77FhD94w9U0H',
                    'yearly_id' => 'price_1Jksq8I2g5BS77FhkBYHLTEq',
                    'yearly_incentive' => 'Save 20%',
                    'features' => [
                        'Feature 1',
                        'Feature 2',
                        'Feature 3',
                    ],
                    'options' => [
                        'database_backups' => true,
                    ],
                    'released' => false, //shows coming soon or released
                    'archived' => false //Hides billable from site
                ],
                [
                    'name' => 'Manage It Pro Skips',
                    'short_description' => 'Manage It Pro Skips License',
                    'monthly_id' => 'price_1Jj3yXI2g5BS77FhNDpdZjXO',
                    'yearly_id' => 'price_1JsF4aI2g5BS77FheuFlWXlx',
                    'yearly_incentive' => 'Save 20%',
                    'features' => [
                        'Feature 1',
                        'Feature 2',
                        'Feature 3',
                    ],
                    'options' => [
                        'database_backups' => true,
                    ],
                    'released' => false, //shows coming soon or released
                    'archived' => false //Hides billable from site
                ],
            ],


        ],
    ]
];
